export const BoardID = '16bf7333-eac2-40e8-9a04-41ba99c042c0'
const endpoint =
    'https://2qgj2kp27f.execute-api.ca-central-1.amazonaws.com/prod/'
export const GetListsUrl = endpoint + 'getLists'
export const GetCardsUrl = endpoint + 'getCards'
export const UpdateListUrl = endpoint + 'updateList'
export const CreateListUrl = endpoint + 'createList'
export const DeleteListUrl = endpoint + 'deleteList'
export const DeleteCardUrl = endpoint + 'deleteCard'
export const CreateCardUrl = endpoint + 'createCard'
export const UpdateCardUrl = endpoint + 'updateCard'
export const GetListOrderUrl = endpoint + 'getListOrder'
export const GetCardOrderUrl = endpoint + 'getCardOrder'
export const UpdateListOrder = endpoint + 'updateListOrder'
export const APIKEY = 'gVEC2aZKAP7VPs1LmgIRx5DY1hjfYevu1vZxxfIM'
export const ListOrder = '69a6857f-c6a8-44e2-a118-d15986a6fa08'
